## Numpy

In [1]:
!pip install numpy

In [4]:
import time
import numpy as np
size = 8000000

# for list
a=list(range(size))

start_l = time.time()
a = list(map(lambda i : i**2,a))
end_l = time.time() - start_l

#array
a=np.arange(size)
start_a = time.time()
a = [a**2]
end_a = time.time() - start_a

print("Time taken by list:",end_l)
print("Time taken by Array:",end_a)

Time taken by list: 3.921367883682251
Time taken by Array: 0.04246091842651367


In [1]:
import numpy as np

In [3]:
# How to create array ------- ans--  .array()

# 12/09/2026

a=[12,34,56]
print(type(a))

<class 'list'>


In [4]:
# array using list

arr=np.array(a)
print(arr)
print(type(arr))

[12 34 56]
<class 'numpy.ndarray'>


In [5]:
arr=np.array([23,45,67])
print(arr)

[23 45 67]


In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Array Attributrs
# 1. ndim

In [7]:
 print(arr.ndim)  # it shows the number of dimensions

1


In [8]:
# 2. Shape
print(arr.shape) # it shows matrix format of array

(10,)


In [9]:
# 3. Size
print(arr.size) # it shows the total elements

10


In [17]:
# 4. dtype
arr3=np.array([23,"34.54",22])
arr1=np.array([22,45,56])
arr2=np.array([22.4,45.5,56])
print(arr3.dtype)
print(arr1.dtype)
print(arr2.dtype)

<U21
int64
float64


In [21]:
# 5. itemsize  it show how much memory a single element is taking 
str_array = np.array(["12","34",45])
float_array = np.array([12.4,3.7,45])
int_array = np.array([12,37,45])

print(str_array.itemsize)
print(float_array.itemsize)
print(int_array.itemsize)

84
8
8


In [23]:
# task
arr23 = np.array([1,2,3,4,5])
print(arr23.size*arr23.itemsize)

40


In [7]:
#15/09/26
# How to Create 2D array 
import numpy as np
arr2 = np.array([[10,20],[30,40],[50,60]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[10 20]
 [30 40]
 [50 60]]
(3, 2)
2


In [5]:
arr3 = np.array([[[10,20,300],[30,40,500],[50,60,600]]])
print(arr3)
print(arr3.shape)


[[[ 10  20 300]
  [ 30  40 500]
  [ 50  60 600]]]
(1, 3, 3)


In [11]:
k = np.arange(1,101)
arr4=np.array(k)
print(k)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [14]:
c = np.arange(0,51,5)
arr5=np.array(c)
print(c)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [17]:
d = np.arange(2,20,2)
arr6=np.array(d)
print(d)

[ 2  4  6  8 10 12 14 16 18]


In [1]:
import numpy as np
aa=np.arange(1,101,10)
print(aa)

[ 1 11 21 31 41 51 61 71 81 91]


In [3]:
aa1=np.arange(3,42,2)
print(aa1)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]


In [5]:
aa2=np.array([[3,4,5],[45,67,87],[7,6,5]])
print(aa2)
print(aa2.ndim)
print(aa2.size)
print(aa2)
print(aa2)
print(aa2)

[[ 3  4  5]
 [45 67 87]
 [ 7  6  5]]


In [2]:
# 16/09/2026
# Creating 2D array using numpy function
import numpy as np
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#--------RESHAPE-------

a=np.arange(1,10).reshape(3,3)
print(a)
#print(a.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
b=np.arange(1,82).reshape(9,9)
print(b)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]
 [55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80 81]]


In [8]:
# -----Random------
# IT GIVES RANDOM VALUES BETWEEN 0 TO 1

n=np.random.random(20).reshape(4,5)
print(n)

[[0.48737268 0.56668845 0.17467218 0.95666412 0.20404121]
 [0.96067047 0.0634917  0.53536643 0.22723018 0.4187622 ]
 [0.81158529 0.77638804 0.48868662 0.54263016 0.35595019]
 [0.28251418 0.54784908 0.33963241 0.97242753 0.43852672]]


In [125]:
# ----Randint----
# IT GIVES RANDOM INTEGER VALUE
# n=np.random.randint(20,51,7)
n=np.random.randint(20,51,8).reshape(4,2)
print(n)

[[29 39]
 [22 46]
 [23 48]
 [38 46]]


In [134]:
# CREATE A ARRAY OF RANDOM INTEGER NUMBERS FROM 1 TO 51 AND RESHAPE THE ARRAY INTO POSSIBLE FORMATS
print(np.random.randint(1,51,36).reshape(2,18))
print(np.random.randint(1,51,36).reshape(18,2))
print(np.random.randint(1,51,36).reshape(3,12))
print(np.random.randint(1,51,36).reshape(12,3))
print(np.random.randint(1,51,36).reshape(4,9))
print(np.random.randint(1,51,36).reshape(9,4))
print(np.random.randint(1,51,36).reshape(6,6))
print(np.random.randint(1,51,36).reshape(1,36))
print(np.random.randint(1,51,36).reshape(36,1))

[[29 41 19 40 25 43  1  1 43 24 33  8 11 17 50 16 40 38]
 [ 7 39  1  5 40 24 16  5 13  6 26 37 36 24 29  2 29 15]]
[[ 5 48]
 [45 11]
 [ 9  5]
 [10 15]
 [17 42]
 [31  1]
 [37 10]
 [11 31]
 [ 1 40]
 [37 22]
 [22 44]
 [11 25]
 [36 36]
 [39 49]
 [13 29]
 [43  1]
 [10 36]
 [30  2]]
[[42 29 15 19 19 43 34 41 35 49 47 41]
 [41  8 35 47 32 41 16  7 26 27 21 27]
 [45 24 31 32 42 25 18  8 41 37 39 15]]
[[29 43 12]
 [17  4 22]
 [48  6 24]
 [48 28 14]
 [38 13 35]
 [47 26 31]
 [ 2 45 25]
 [ 9 49 31]
 [ 4 36 27]
 [46 23 14]
 [27 23 41]
 [ 7  3 35]]
[[44 27 47 46 24 20 12 32 23]
 [48  1 18  2  1 48 47 16 28]
 [10 20 23 50 47 38 30 50  7]
 [24 22 13  9  2 50 42 26 22]]
[[15 20  8 47]
 [45 18 22 24]
 [13  5 38  5]
 [43 47 15  7]
 [26  5 50  2]
 [ 4  4 34 46]
 [ 5 13 37 38]
 [ 1  9  5 30]
 [20 49 47 19]]
[[22 28 48 35 18 31]
 [17 36 50 30 13 31]
 [ 6 23 44 17 21 16]
 [18 11  9  6 23  1]
 [50 22 11 29 49 20]
 [46 20  2 24  6 37]]
[[32 43 48 14 40 16 28 14 16 49 44 18 31  8 36  5 15  4 26 14  9 43 37 28
 

In [138]:
#--------ZEROS-------

a=np.zeros(4).reshape(2,2)
print(a)

a=np.zeros((4,4))
print(a)


[[0. 0.]
 [0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [141]:
# CREATE A ARRAY OF ZEROS OF MATRIX FORMAT 5,5 USING 1ST RESHAPE AND THEN WITHOUT USING RESHAPE
a=np.zeros(25).reshape(5,5)
print(a)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [146]:
ai = np.zeros((5,5))
print(ai)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [147]:
# ----Ones----
aa=np.ones(4).reshape(2,2)
print(aa)

aii=np.ones((4,4))
print(aii)

[[1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#Task
import numpy as np
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
arr=np.ones((3,6))
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [8]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,19,22,34]])
print(arr)
print(arr.reshape(3,4))

[[ 1  2  3  4  5  6]
 [ 7  8  9 19 22 34]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 19 22 34]]


In [17]:
ar12=np.arange(0,22,2)
print(ar12)
print(ar12.reshape(1,11))
print(ar12.reshape(11,1))

[ 0  2  4  6  8 10 12 14 16 18 20]
[[ 0  2  4  6  8 10 12 14 16 18 20]]
[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]]


In [23]:
n=np.random.randint(10,50,16).reshape(4,4)
print(n)

[[35 11 25 39]
 [36 44 48 26]
 [17 21 26 24]
 [26 47 46 26]]
