In [1]:
import numpy as np

In [3]:
# Q1. Replace all odd numbers in the given array with -1
 # input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 # expected Output->[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

n=np.array([0,1,2,3,4,5,6,7,8,9])
np.where(n%2!=0,-1,n)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [5]:
#Q2. Convert a 1-D array into a 2-D array with 3 rows
# input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]) output = [[ 0, 1, 2],[3, 4, 5],[6, 7, 8]]
input = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3,3)
print(input)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Q3. Create a 2-D array with 202 to all the values
# Output = [[202, 202],[202, 202]]

n=np.full((2,2),202)
print(n)

[[202 202]
 [202 202]]


In [9]:
# Q4. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
# output = [36, 30, 36, 38, 31, 35, 36, 30, 32, 34]

n=np.random.randint(30,40,10)
print(n)

[30 38 31 32 39 37 39 34 38 33]


In [11]:
# Q.6 Create a null vector of size 10
# output = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

k=np.zeros(10)
print(k)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
# Q.7 Create a null vector of size 10 but the fifth value which is 1
# output = [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]

arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
# Q.8 Reverse a vector (first element becomes last)
arr=np.random.randint(23,45,10)
print(arr)
print(arr[::-1])

[35 44 38 39 29 32 27 28 38 29]
[29 38 28 27 32 29 39 38 44 35]


In [17]:
# Q.9 Create a 3x3 identity matrix
n=np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# Q.11 Create a 10x10 array with random values and find the minimum and maximum values
ran=np.random.randint(20,56,(10,5))
print(ran)
print(np.max(ran))
print(np.min(ran))


[[31 37 40 31 22]
 [32 31 32 25 54]
 [45 48 54 45 25]
 [47 35 40 47 51]
 [55 32 22 55 29]
 [26 33 48 48 40]
 [48 43 52 54 51]
 [49 39 34 42 34]
 [42 49 43 21 41]
 [43 28 36 50 28]]
55
21


In [27]:
n=np.zeros((3,3),dtype=int)
print(n)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [30]:
import numpy as np
j=np.ones((4,4))
j[1:3,1:3]=0
print(j)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [2]:
import numpy as np

a=np.array([1,2,3,34,5,56,7,6,8,7])
print(a)

[ 1  2  3 34  5 56  7  6  8  7]


In [4]:
a=np.array(["hii",233,34.5])
print(a)
print(a.dtype)

['hii' '233' '34.5']
<U32


In [9]:
a=np.arange(1,42,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]


In [10]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
a=np.ones((3,6))
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [15]:
a=np.array([[1,2,3,4,5,6],[7,8,9,0,6,2]]).reshape(3,4)
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 6 2]]


In [20]:
a=np.arange(0,20,2)
print(a)
print(a.reshape(2,5))
print(a.reshape(5,2))
# print(a.reshape(1,10))
# print(a.reshape(10,1))

[ 0  2  4  6  8 10 12 14 16 18]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [23]:
a=np.random.randint(23,45,(4,4))
print(a)

[[29 37 34 27]
 [42 29 25 33]
 [30 24 41 42]
 [23 32 25 43]]


In [25]:
a=np.random.randint(10,25,(3,3))
print(a)
print(a[a%2==0])

[[12 18 15]
 [13 19 24]
 [11 13 12]]
[12 18 24 12]


In [27]:
a=np.random.randint(10,25,(4,4))
print(a)
print(a[a%2==0])
print(a[a%2!=0])

[[24 13 21 14]
 [19 21 14 17]
 [17 15 12 11]
 [20 18 22 14]]
[24 14 14 12 20 18 22 14]
[13 21 19 21 17 17 15 11]


In [37]:
a=np.ones((5,5))
print(a)
a[1:4,1:4]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
a=np.ones((5,5))
print(a*5)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [62]:
a=np.random.randint(23,45,(2,3))
for i in np.nditer(a):
    print(i)

42
26
26
26
33
36


In [64]:
a=np.random.randint(20,34,(5,5))
print(a)
print(a-5)

[[22 25 29 22 26]
 [20 31 31 25 27]
 [31 29 24 32 20]
 [25 23 29 32 33]
 [25 28 32 23 20]]
[[17 20 24 17 21]
 [15 26 26 20 22]
 [26 24 19 27 15]
 [20 18 24 27 28]
 [20 23 27 18 15]]
